In [51]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [52]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [53]:
print(x)

[['Indonesia' 34.0 71000.0]
 ['Japan' 17.0 47000.0]
 ['Korea' 20.0 53000.0]
 ['Japan' 28.0 60000.0]
 ['Korea' 30.0 nan]
 ['Indonesia' 25.0 57000.0]
 ['Japan' nan 51000.0]
 ['Indonesia' 38.0 78000.0]
 ['Korea' 40.0 82000.0]
 ['Indonesia' 27.0 66000.0]]


In [54]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [55]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [56]:
print(x)

[['Indonesia' 34.0 71000.0]
 ['Japan' 17.0 47000.0]
 ['Korea' 20.0 53000.0]
 ['Japan' 28.0 60000.0]
 ['Korea' 30.0 62777.77777777778]
 ['Indonesia' 25.0 57000.0]
 ['Japan' 28.77777777777778 51000.0]
 ['Indonesia' 38.0 78000.0]
 ['Korea' 40.0 82000.0]
 ['Indonesia' 27.0 66000.0]]


In [57]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [58]:
print(x)

[[1.0 0.0 0.0 34.0 71000.0]
 [0.0 1.0 0.0 17.0 47000.0]
 [0.0 0.0 1.0 20.0 53000.0]
 [0.0 1.0 0.0 28.0 60000.0]
 [0.0 0.0 1.0 30.0 62777.77777777778]
 [1.0 0.0 0.0 25.0 57000.0]
 [0.0 1.0 0.0 28.77777777777778 51000.0]
 [1.0 0.0 0.0 38.0 78000.0]
 [0.0 0.0 1.0 40.0 82000.0]
 [1.0 0.0 0.0 27.0 66000.0]]


In [59]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [60]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [61]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [44]:
print(x_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [62]:
print(x_test)

[[0.0 0.0 1.0 20.0 53000.0]
 [1.0 0.0 0.0 27.0 66000.0]]


In [63]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [64]:
print(y_test)

[0 1]


In [65]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [66]:
print(x_train)

[[0.0 1.0 0.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 0.0 1.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 1.0 0.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 1.0 0.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 0.0 1.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [67]:
print(x_test)

[[0.0 0.0 1.0 -1.4661817944830124 -0.9069571034860727]
 [1.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]
